export const seedMovies = [
  {
    title: 'Neon Odyssey',
    description: 'In a sprawling cyberpunk metropolis, an augmented detective uncovers a conspiracy that threatens the boundary between human consciousness and artificial life.',
    poster: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-11-15',
    rating: 'PG-13',
    duration: '2h 18m',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    type: 'movie',
    featured: true,
    popularity: 98
  },
  {
    title: 'Shadows of the Citadel',
    description: 'An elite cadre of defenders must protect an ancient mountaintop fortress from an enigmatic siege force wielding forgotten arcane technologies.',
    poster: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-08-20',
    rating: 'PG-13',
    duration: '2h 05m',
    genres: ['Action', 'Fantasy'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    type: 'movie',
    featured: false,
    popularity: 94
  },
  {
    title: 'The Crimson Horizon',
    description: 'A rogue astronaut team undertakes a perilous one-way orbital mission to rescue the sole survivor of Mars Base Alpha before solar winds wipe out communications.',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-06-12',
    rating: 'PG-13',
    duration: '2h 12m',
    genres: ['Sci-Fi', 'Drama'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    type: 'movie',
    featured: false,
    popularity: 91
  },
  {
    title: 'Midnight in Montmartre',
    description: 'Two jazz musicians cross paths in 1950s Paris, embarking on an improvised tour of subterranean clubs that transforms both their art and their lives.',
    poster: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2024-12-05',
    rating: 'PG',
    duration: '1h 52m',
    genres: ['Drama', 'Romance'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'movie',
    featured: false,
    popularity: 84
  },
  {
    title: 'Whispering Woods',
    description: 'During a weekend retreat in the Pacific Northwest, four childhood friends discover their old hideout holds a chilling supernatural secret.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-10-31',
    rating: 'R',
    duration: '1h 44m',
    genres: ['Horror', 'Thriller'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    type: 'movie',
    featured: false,
    popularity: 87
  },
  {
    title: 'The Great Pet Caper',
    description: 'When their neighborhood bakery faces foreclosure, a plucky golden retriever and a cynical alley cat mastermind an improbable jewel heist to save it.',
    poster: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-04-18',
    rating: 'PG',
    duration: '1h 36m',
    genres: ['Animation', 'Comedy'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    type: 'movie',
    featured: false,
    popularity: 89
  },
  {
    title: 'Velocity Zero',
    description: 'A former Formula 1 prodigy forced into getaway driving must navigate a high-octane escape route through European backroads with ruthless pursuers on his tail.',
    poster: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-07-04',
    rating: 'PG-13',
    duration: '2h 02m',
    genres: ['Action', 'Thriller'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    type: 'movie',
    featured: false,
    popularity: 92
  },
  {
    title: 'Laughing Gas Station',
    description: 'Working the graveyard shift at an eccentric remote highway gas station turns into an absurd night of wacky tourists, bizarre deliveries, and accidental comedy.',
    poster: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-03-22',
    rating: 'PG-13',
    duration: '1h 38m',
    genres: ['Comedy'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'movie',
    featured: false,
    popularity: 79
  },
  {
    title: 'Echoes of the Deep',
    description: 'Oceanographers aboard an ultra-deep research submarine detect rhythmic bio-acoustic signals emanating from the bottom of the Mariana Trench.',
    poster: 'https://images.unsplash.com/photo-1682687220063-4742bd7fd538?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-09-10',
    rating: 'PG-13',
    duration: '1h 58m',
    genres: ['Sci-Fi', 'Thriller'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    type: 'movie',
    featured: false,
    popularity: 88
  },
  {
    title: 'The Silent Canvas',
    description: 'An insightful, intimate documentary tracing the life and creative revolution of an anonymous muralist whose street art ignited an international cultural movement.',
    poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2024-10-14',
    rating: 'PG',
    duration: '1h 45m',
    genres: ['Documentaries'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    type: 'movie',
    featured: false,
    popularity: 76
  },
  {
    title: 'Chronicles of Valoria',
    description: 'A young blacksmith discovers a broken celestial relic that marks her as the sole heir capable of re-forging the barrier shielding her realm from mythical dragons.',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-01-30',
    rating: 'PG-13',
    duration: '2h 25m',
    genres: ['Fantasy', 'Action'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    type: 'movie',
    featured: false,
    popularity: 90
  },
  {
    title: 'Culinary Chaos',
    description: 'Two rival Michelin-starred chefs are unintentionally hired to run the same luxury destination kitchen during a high-stakes presidential summit.',
    poster: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2024-11-20',
    rating: 'PG-13',
    duration: '1h 48m',
    genres: ['Comedy', 'Romance'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'movie',
    featured: false,
    popularity: 82
  },
  {
    title: 'The Quantum Paradox',
    description: 'A theoretical physicist accidentally splits her timeline, forcing her to outsmart alternate versions of herself before temporal collapse tears reality apart.',
    poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1507499739999-097706ad8914?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-05-19',
    rating: 'PG-13',
    duration: '2h 10m',
    genres: ['Sci-Fi', 'Thriller'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    type: 'movie',
    featured: false,
    popularity: 95
  },
  {
    title: 'Wild Frontier',
    description: 'An extraordinary nature documentary captured with specialized camera drones showcasing the rarest migrations across untamed Arctic tundras.',
    poster: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2024-09-01',
    rating: 'G',
    duration: '1h 32m',
    genres: ['Documentaries'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    type: 'movie',
    featured: false,
    popularity: 75
  },
  {
    title: 'Paper Dragons',
    description: 'An enchanted origami dragon springs to life in a Tokyo antique shop, guiding a lonely young illustrator through a magical realm of childhood memories.',
    poster: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-02-14',
    rating: 'PG',
    duration: '1h 42m',
    genres: ['Animation', 'Fantasy'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    type: 'movie',
    featured: false,
    popularity: 86
  },
  {
    title: 'Undercover Billionaire',
    description: 'A tech mogul goes undercover as an entry-level courier in his own logistics empire, only to discover workplace sabotage orchestrated by his closest executives.',
    poster: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2024-08-15',
    rating: 'PG-13',
    duration: '1h 55m',
    genres: ['Comedy', 'Drama'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: 'movie',
    featured: false,
    popularity: 80
  },
  {
    title: 'The Forgotten Sector',
    description: 'Deep within abandoned sub-levels of an automated orbital mining station, a reclamation crew makes first contact with an evolved non-terrestrial ecosystem.',
    poster: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-04-05',
    rating: 'R',
    duration: '2h 00m',
    genres: ['Sci-Fi', 'Horror'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    type: 'movie',
    featured: false,
    popularity: 85
  },
  {
    title: 'Last Stand at Blackwood',
    description: 'A retired sheriff and a ragtag band of townspeople take a defiant stand against a heavily armed cartel syndicate on a stormy winter night.',
    poster: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    releaseDate: '2025-06-25',
    rating: 'R',
    duration: '1h 56m',
    genres: ['Action', 'Thriller'],
    trailer: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    video: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    type: 'movie',
    featured: false,
    popularity: 89
  }
];

export default seedMovies;
